on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "azb"
  homebrew:
    needs: releases-matrix
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: azb
          homebrew-tap: jcanizalez/homebrew-cli
          download-url: https://github.com/jcanizalez/azb-cli/releases/download/${{ github.event.release.tag_name }}/azb-${{ github.event.release.tag_name }}-darwin-amd64.tar.gz
          commit-message: |
            Updated {{formulaName}} to {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.TOKEN }}
